/*
 * NajotEdu
 *
 * NajotEdu description
 *
 * The version of the OpenAPI document: V1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using NajotEdu.Client.Model;
using NajotEdu.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace NajotEdu.Client.Test.Model
{
    /// <summary>
    ///  Class for testing AddStudentGroupModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddStudentGroupModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AddStudentGroupModel
        //private AddStudentGroupModel instance;

        public AddStudentGroupModelTests()
        {
            // TODO uncomment below to create an instance of AddStudentGroupModel
            //instance = new AddStudentGroupModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AddStudentGroupModel
        /// </summary>
        [Fact]
        public void AddStudentGroupModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" AddStudentGroupModel
            //Assert.IsType<AddStudentGroupModel>(instance);
        }

        /// <summary>
        /// Test the property 'StudentId'
        /// </summary>
        [Fact]
        public void StudentIdTest()
        {
            // TODO unit test for the property 'StudentId'
        }

        /// <summary>
        /// Test the property 'IsPayed'
        /// </summary>
        [Fact]
        public void IsPayedTest()
        {
            // TODO unit test for the property 'IsPayed'
        }

        /// <summary>
        /// Test the property 'JoinedDate'
        /// </summary>
        [Fact]
        public void JoinedDateTest()
        {
            // TODO unit test for the property 'JoinedDate'
        }
    }
}
