/*
 * NajotEdu
 *
 * NajotEdu description
 *
 * The version of the OpenAPI document: V1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using NajotEdu.Client.Model;
using NajotEdu.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace NajotEdu.Client.Test.Model
{
    /// <summary>
    ///  Class for testing AttendenceCheckModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AttendenceCheckModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AttendenceCheckModel
        //private AttendenceCheckModel instance;

        public AttendenceCheckModelTests()
        {
            // TODO uncomment below to create an instance of AttendenceCheckModel
            //instance = new AttendenceCheckModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AttendenceCheckModel
        /// </summary>
        [Fact]
        public void AttendenceCheckModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" AttendenceCheckModel
            //Assert.IsType<AttendenceCheckModel>(instance);
        }

        /// <summary>
        /// Test the property 'StudentId'
        /// </summary>
        [Fact]
        public void StudentIdTest()
        {
            // TODO unit test for the property 'StudentId'
        }

        /// <summary>
        /// Test the property 'HasParticipated'
        /// </summary>
        [Fact]
        public void HasParticipatedTest()
        {
            // TODO unit test for the property 'HasParticipated'
        }
    }
}
