/*
 * NajotEdu
 *
 * NajotEdu description
 *
 * The version of the OpenAPI document: V1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using NajotEdu.Client.Model;
using NajotEdu.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace NajotEdu.Client.Test.Model
{
    /// <summary>
    ///  Class for testing CreateGroupModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateGroupModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateGroupModel
        //private CreateGroupModel instance;

        public CreateGroupModelTests()
        {
            // TODO uncomment below to create an instance of CreateGroupModel
            //instance = new CreateGroupModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateGroupModel
        /// </summary>
        [Fact]
        public void CreateGroupModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateGroupModel
            //Assert.IsType<CreateGroupModel>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Fact]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }

        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Fact]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }

        /// <summary>
        /// Test the property 'TeacherId'
        /// </summary>
        [Fact]
        public void TeacherIdTest()
        {
            // TODO unit test for the property 'TeacherId'
        }

        /// <summary>
        /// Test the property 'LessonStartTime'
        /// </summary>
        [Fact]
        public void LessonStartTimeTest()
        {
            // TODO unit test for the property 'LessonStartTime'
        }

        /// <summary>
        /// Test the property 'LessonEndTime'
        /// </summary>
        [Fact]
        public void LessonEndTimeTest()
        {
            // TODO unit test for the property 'LessonEndTime'
        }
    }
}
