/*
 * NajotEdu
 *
 * NajotEdu description
 *
 * The version of the OpenAPI document: V1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using NajotEdu.Client.Model;
using NajotEdu.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace NajotEdu.Client.Test.Model
{
    /// <summary>
    ///  Class for testing CreateStudentModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateStudentModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateStudentModel
        //private CreateStudentModel instance;

        public CreateStudentModelTests()
        {
            // TODO uncomment below to create an instance of CreateStudentModel
            //instance = new CreateStudentModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateStudentModel
        /// </summary>
        [Fact]
        public void CreateStudentModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateStudentModel
            //Assert.IsType<CreateStudentModel>(instance);
        }

        /// <summary>
        /// Test the property 'FullName'
        /// </summary>
        [Fact]
        public void FullNameTest()
        {
            // TODO unit test for the property 'FullName'
        }

        /// <summary>
        /// Test the property 'CreatedDate'
        /// </summary>
        [Fact]
        public void CreatedDateTest()
        {
            // TODO unit test for the property 'CreatedDate'
        }

        /// <summary>
        /// Test the property 'BirthDate'
        /// </summary>
        [Fact]
        public void BirthDateTest()
        {
            // TODO unit test for the property 'BirthDate'
        }

        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Fact]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }
    }
}
