/*
 * NajotEdu
 *
 * NajotEdu description
 *
 * The version of the OpenAPI document: V1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using NajotEdu.Client.Model;
using NajotEdu.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace NajotEdu.Client.Test.Model
{
    /// <summary>
    ///  Class for testing DoAttendenceCheckModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DoAttendenceCheckModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DoAttendenceCheckModel
        //private DoAttendenceCheckModel instance;

        public DoAttendenceCheckModelTests()
        {
            // TODO uncomment below to create an instance of DoAttendenceCheckModel
            //instance = new DoAttendenceCheckModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DoAttendenceCheckModel
        /// </summary>
        [Fact]
        public void DoAttendenceCheckModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" DoAttendenceCheckModel
            //Assert.IsType<DoAttendenceCheckModel>(instance);
        }

        /// <summary>
        /// Test the property 'LessonId'
        /// </summary>
        [Fact]
        public void LessonIdTest()
        {
            // TODO unit test for the property 'LessonId'
        }

        /// <summary>
        /// Test the property 'Checks'
        /// </summary>
        [Fact]
        public void ChecksTest()
        {
            // TODO unit test for the property 'Checks'
        }
    }
}
