/*
 * NajotEdu
 *
 * NajotEdu description
 *
 * The version of the OpenAPI document: V1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using NajotEdu.Client.Model;
using NajotEdu.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace NajotEdu.Client.Test.Model
{
    /// <summary>
    ///  Class for testing LoginRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LoginRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LoginRequest
        //private LoginRequest instance;

        public LoginRequestTests()
        {
            // TODO uncomment below to create an instance of LoginRequest
            //instance = new LoginRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LoginRequest
        /// </summary>
        [Fact]
        public void LoginRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" LoginRequest
            //Assert.IsType<LoginRequest>(instance);
        }

        /// <summary>
        /// Test the property 'UserName'
        /// </summary>
        [Fact]
        public void UserNameTest()
        {
            // TODO unit test for the property 'UserName'
        }

        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
    }
}
