/*
 * NajotEdu
 *
 * NajotEdu description
 *
 * The version of the OpenAPI document: V1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using NajotEdu.Client.Model;
using NajotEdu.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace NajotEdu.Client.Test.Model
{
    /// <summary>
    ///  Class for testing TimeSpan
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TimeSpanTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TimeSpan
        //private TimeSpan instance;

        public TimeSpanTests()
        {
            // TODO uncomment below to create an instance of TimeSpan
            //instance = new TimeSpan();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TimeSpan
        /// </summary>
        [Fact]
        public void TimeSpanInstanceTest()
        {
            // TODO uncomment below to test "IsType" TimeSpan
            //Assert.IsType<TimeSpan>(instance);
        }

        /// <summary>
        /// Test the property 'Ticks'
        /// </summary>
        [Fact]
        public void TicksTest()
        {
            // TODO unit test for the property 'Ticks'
        }

        /// <summary>
        /// Test the property 'Days'
        /// </summary>
        [Fact]
        public void DaysTest()
        {
            // TODO unit test for the property 'Days'
        }

        /// <summary>
        /// Test the property 'Hours'
        /// </summary>
        [Fact]
        public void HoursTest()
        {
            // TODO unit test for the property 'Hours'
        }

        /// <summary>
        /// Test the property 'Milliseconds'
        /// </summary>
        [Fact]
        public void MillisecondsTest()
        {
            // TODO unit test for the property 'Milliseconds'
        }

        /// <summary>
        /// Test the property 'Minutes'
        /// </summary>
        [Fact]
        public void MinutesTest()
        {
            // TODO unit test for the property 'Minutes'
        }

        /// <summary>
        /// Test the property 'Seconds'
        /// </summary>
        [Fact]
        public void SecondsTest()
        {
            // TODO unit test for the property 'Seconds'
        }

        /// <summary>
        /// Test the property 'TotalDays'
        /// </summary>
        [Fact]
        public void TotalDaysTest()
        {
            // TODO unit test for the property 'TotalDays'
        }

        /// <summary>
        /// Test the property 'TotalHours'
        /// </summary>
        [Fact]
        public void TotalHoursTest()
        {
            // TODO unit test for the property 'TotalHours'
        }

        /// <summary>
        /// Test the property 'TotalMilliseconds'
        /// </summary>
        [Fact]
        public void TotalMillisecondsTest()
        {
            // TODO unit test for the property 'TotalMilliseconds'
        }

        /// <summary>
        /// Test the property 'TotalMinutes'
        /// </summary>
        [Fact]
        public void TotalMinutesTest()
        {
            // TODO unit test for the property 'TotalMinutes'
        }

        /// <summary>
        /// Test the property 'TotalSeconds'
        /// </summary>
        [Fact]
        public void TotalSecondsTest()
        {
            // TODO unit test for the property 'TotalSeconds'
        }
    }
}
