/*
 * NajotEdu
 *
 * NajotEdu description
 *
 * The version of the OpenAPI document: V1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using NajotEdu.Client.Client;
using NajotEdu.Client.Api;
// uncomment below to import models
//using NajotEdu.Client.Model;

namespace NajotEdu.Client.Test.Api
{
    /// <summary>
    ///  Class for testing AttendanceApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AttendanceApiTests : IDisposable
    {
        private AttendanceApi instance;

        public AttendanceApiTests()
        {
            instance = new AttendanceApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AttendanceApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AttendanceApi
            //Assert.IsType<AttendanceApi>(instance);
        }

        /// <summary>
        /// Test ApiAttendanceCheckPost
        /// </summary>
        [Fact]
        public void ApiAttendanceCheckPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DoAttendenceCheckModel? doAttendenceCheckModel = null;
            //instance.ApiAttendanceCheckPost(doAttendenceCheckModel);
        }
    }
}
