/*
 * NajotEdu
 *
 * NajotEdu description
 *
 * The version of the OpenAPI document: V1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using NajotEdu.Client.Client;
using NajotEdu.Client.Api;
// uncomment below to import models
//using NajotEdu.Client.Model;

namespace NajotEdu.Client.Test.Api
{
    /// <summary>
    ///  Class for testing GroupApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class GroupApiTests : IDisposable
    {
        private GroupApi instance;

        public GroupApiTests()
        {
            instance = new GroupApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GroupApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' GroupApi
            //Assert.IsType<GroupApi>(instance);
        }

        /// <summary>
        /// Test ApiGroupGetAllGet
        /// </summary>
        [Fact]
        public void ApiGroupGetAllGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.ApiGroupGetAllGet();
        }

        /// <summary>
        /// Test ApiGroupGroupIdLessonsGet
        /// </summary>
        [Fact]
        public void ApiGroupGroupIdLessonsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int groupId = null;
            //instance.ApiGroupGroupIdLessonsGet(groupId);
        }

        /// <summary>
        /// Test ApiGroupGroupIdStudentDelete
        /// </summary>
        [Fact]
        public void ApiGroupGroupIdStudentDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int groupId = null;
            //int? studentId = null;
            //instance.ApiGroupGroupIdStudentDelete(groupId, studentId);
        }

        /// <summary>
        /// Test ApiGroupGroupIdStudentPost
        /// </summary>
        [Fact]
        public void ApiGroupGroupIdStudentPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int groupId = null;
            //AddStudentGroupModel? addStudentGroupModel = null;
            //instance.ApiGroupGroupIdStudentPost(groupId, addStudentGroupModel);
        }

        /// <summary>
        /// Test ApiGroupIdDelete
        /// </summary>
        [Fact]
        public void ApiGroupIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //int? id2 = null;
            //instance.ApiGroupIdDelete(id, id2);
        }

        /// <summary>
        /// Test ApiGroupIdGet
        /// </summary>
        [Fact]
        public void ApiGroupIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //instance.ApiGroupIdGet(id);
        }

        /// <summary>
        /// Test ApiGroupPost
        /// </summary>
        [Fact]
        public void ApiGroupPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateGroupModel? createGroupModel = null;
            //instance.ApiGroupPost(createGroupModel);
        }

        /// <summary>
        /// Test ApiGroupPut
        /// </summary>
        [Fact]
        public void ApiGroupPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //string? name = null;
            //DateTime? startDate = null;
            //DateTime? endDate = null;
            //int? teacherId = null;
            //instance.ApiGroupPut(id, name, startDate, endDate, teacherId);
        }
    }
}
