/*
 * NajotEdu
 *
 * NajotEdu description
 *
 * The version of the OpenAPI document: V1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using NajotEdu.Client.Client;
using NajotEdu.Client.Api;
// uncomment below to import models
//using NajotEdu.Client.Model;

namespace NajotEdu.Client.Test.Api
{
    /// <summary>
    ///  Class for testing StudentApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class StudentApiTests : IDisposable
    {
        private StudentApi instance;

        public StudentApiTests()
        {
            instance = new StudentApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StudentApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' StudentApi
            //Assert.IsType<StudentApi>(instance);
        }

        /// <summary>
        /// Test ApiStudentGetAllGet
        /// </summary>
        [Fact]
        public void ApiStudentGetAllGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.ApiStudentGetAllGet();
        }

        /// <summary>
        /// Test ApiStudentGetByIdGet
        /// </summary>
        [Fact]
        public void ApiStudentGetByIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //instance.ApiStudentGetByIdGet(id);
        }

        /// <summary>
        /// Test ApiStudentIdDelete
        /// </summary>
        [Fact]
        public void ApiStudentIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //instance.ApiStudentIdDelete(id);
        }

        /// <summary>
        /// Test ApiStudentPost
        /// </summary>
        [Fact]
        public void ApiStudentPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateStudentModel? createStudentModel = null;
            //instance.ApiStudentPost(createStudentModel);
        }

        /// <summary>
        /// Test ApiStudentPut
        /// </summary>
        [Fact]
        public void ApiStudentPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UpdateStudentModel? updateStudentModel = null;
            //instance.ApiStudentPut(updateStudentModel);
        }
    }
}
