/*
 * NajotEdu
 *
 * NajotEdu description
 *
 * The version of the OpenAPI document: V1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using NajotEdu.Client.Client;
using NajotEdu.Client.Api;
// uncomment below to import models
//using NajotEdu.Client.Model;

namespace NajotEdu.Client.Test.Api
{
    /// <summary>
    ///  Class for testing TeacherApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class TeacherApiTests : IDisposable
    {
        private TeacherApi instance;

        public TeacherApiTests()
        {
            instance = new TeacherApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TeacherApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' TeacherApi
            //Assert.IsType<TeacherApi>(instance);
        }

        /// <summary>
        /// Test ApiTeacherGetAllGet
        /// </summary>
        [Fact]
        public void ApiTeacherGetAllGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.ApiTeacherGetAllGet();
        }

        /// <summary>
        /// Test ApiTeacherGetByIdGet
        /// </summary>
        [Fact]
        public void ApiTeacherGetByIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //instance.ApiTeacherGetByIdGet(id);
        }

        /// <summary>
        /// Test ApiTeacherIdDelete
        /// </summary>
        [Fact]
        public void ApiTeacherIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //instance.ApiTeacherIdDelete(id);
        }

        /// <summary>
        /// Test ApiTeacherPost
        /// </summary>
        [Fact]
        public void ApiTeacherPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateTeacherModel? createTeacherModel = null;
            //instance.ApiTeacherPost(createTeacherModel);
        }

        /// <summary>
        /// Test ApiTeacherPut
        /// </summary>
        [Fact]
        public void ApiTeacherPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UpdateTeacherModel? updateTeacherModel = null;
            //instance.ApiTeacherPut(updateTeacherModel);
        }
    }
}
