/*
 * NajotEdu
 *
 * NajotEdu description
 *
 * The version of the OpenAPI document: V1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = NajotEdu.Client.Client.FileParameter;
using OpenAPIDateConverter = NajotEdu.Client.Client.OpenAPIDateConverter;

namespace NajotEdu.Client.Model
{
    /// <summary>
    /// AddStudentGroupModel
    /// </summary>
    [DataContract(Name = "AddStudentGroupModel")]
    public partial class AddStudentGroupModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AddStudentGroupModel" /> class.
        /// </summary>
        /// <param name="studentId">studentId.</param>
        /// <param name="isPayed">isPayed.</param>
        /// <param name="joinedDate">joinedDate.</param>
        public AddStudentGroupModel(int studentId = default(int), bool isPayed = default(bool), DateTime joinedDate = default(DateTime))
        {
            this.StudentId = studentId;
            this.IsPayed = isPayed;
            this.JoinedDate = joinedDate;
        }

        /// <summary>
        /// Gets or Sets StudentId
        /// </summary>
        [DataMember(Name = "studentId", EmitDefaultValue = false)]
        public int StudentId { get; set; }

        /// <summary>
        /// Gets or Sets IsPayed
        /// </summary>
        [DataMember(Name = "isPayed", EmitDefaultValue = true)]
        public bool IsPayed { get; set; }

        /// <summary>
        /// Gets or Sets JoinedDate
        /// </summary>
        [DataMember(Name = "joinedDate", EmitDefaultValue = false)]
        public DateTime JoinedDate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AddStudentGroupModel {\n");
            sb.Append("  StudentId: ").Append(StudentId).Append("\n");
            sb.Append("  IsPayed: ").Append(IsPayed).Append("\n");
            sb.Append("  JoinedDate: ").Append(JoinedDate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
