/*
 * NajotEdu
 *
 * NajotEdu description
 *
 * The version of the OpenAPI document: V1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = NajotEdu.Client.Client.FileParameter;
using OpenAPIDateConverter = NajotEdu.Client.Client.OpenAPIDateConverter;

namespace NajotEdu.Client.Model
{
    /// <summary>
    /// AttendenceCheckModel
    /// </summary>
    [DataContract(Name = "AttendenceCheckModel")]
    public partial class AttendenceCheckModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AttendenceCheckModel" /> class.
        /// </summary>
        /// <param name="studentId">studentId.</param>
        /// <param name="hasParticipated">hasParticipated.</param>
        public AttendenceCheckModel(int studentId = default(int), bool hasParticipated = default(bool))
        {
            this.StudentId = studentId;
            this.HasParticipated = hasParticipated;
        }

        /// <summary>
        /// Gets or Sets StudentId
        /// </summary>
        [DataMember(Name = "studentId", EmitDefaultValue = false)]
        public int StudentId { get; set; }

        /// <summary>
        /// Gets or Sets HasParticipated
        /// </summary>
        [DataMember(Name = "hasParticipated", EmitDefaultValue = true)]
        public bool HasParticipated { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AttendenceCheckModel {\n");
            sb.Append("  StudentId: ").Append(StudentId).Append("\n");
            sb.Append("  HasParticipated: ").Append(HasParticipated).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
